version: '3.9'

services:
  ros1_noetic:
    build:
      context: .
      dockerfile: Dockerfile.noetic
    container_name: ros1_noetic
    networks:
      - ros_network
    volumes:
      - .:/root/workspace  # Mount workspace
      # - ./workspace:/root/workspace  # Mount workspace
    environment:
      - ROS_MASTER_URI=http://ros1_noetic:11311
    tty: true

  ros2_humble:
    build:
      context: .
      dockerfile: Dockerfile.humble
    container_name: ros2_humble
    networks:
      - ros_network
    volumes:
      - .:/root/workspace  # Mount workspace
      # - ./workspace:/root/workspace  # Mount workspace
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_DOMAIN_ID=0
      - SDL_AUDIODRIVER=dummy
      - PULSE_SERVER=
      - ALSA_PCM_CARD=0
      - ALSA_CARD=0
      - AUDIODEV=null
      - AUDIODRIVER=dummy
    tty: true

networks:
  ros_network:
    driver: bridge
